(() => {
  const DB_NAME='eikomiCoachMaterials', STORE='rulesMaterials';
  const TYPES={info:'基本情報',vocab:'読む前語彙',sentences:'本文音読和訳',questions:'本書問題',summaries:'超要約解説',quick:'さくっと精読',gachi:'ガチ精読文',chunks:'ガチ精読チャンク',tables:'表データ',notes:'Notes',rules:'全84ルール辞書'};
  const OPTIONAL_TYPES=new Set(['tables','notes']);
  function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,2);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'lessonId'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
  function parseCsv(text){text=String(text).replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>v!==''))rows.push(row);row=[];}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}if(!rows.length)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])));}
  const versionScore=name=>{const m=String(name).match(/_v(\d+)(?:[_\.](\d+))?/i);return m?Number(m[1])*1000+Number(m[2]||0):0;};
  function pickLatest(files,label){return files.filter(f=>f.name.includes(label)&&f.name.toLowerCase().endsWith('.csv')).sort((a,b)=>versionScore(b.name)-versionScore(a.name))[0];}
  async function inflateRaw(bytes){if(typeof DecompressionStream==='undefined')throw new Error('このブラウザではZIP展開に対応していません。CSV個別選択をご利用ください。');const ds=new DecompressionStream('deflate-raw');const ab=await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer();return new Uint8Array(ab);}
  async function unzipFile(file){const buf=new Uint8Array(await file.arrayBuffer()),dv=new DataView(buf.buffer,buf.byteOffset,buf.byteLength);let eocd=-1;for(let i=buf.length-22;i>=Math.max(0,buf.length-65557);i--){if(dv.getUint32(i,true)===0x06054b50){eocd=i;break;}}if(eocd<0)throw new Error('ZIPの終端情報を読み取れませんでした。');const total=dv.getUint16(eocd+10,true),centralOffset=dv.getUint32(eocd+16,true),decoder=new TextDecoder('utf-8');let pos=centralOffset;const out=[];for(let n=0;n<total;n++){if(dv.getUint32(pos,true)!==0x02014b50)throw new Error('ZIPのファイル一覧を読み取れませんでした。');const flags=dv.getUint16(pos+8,true),method=dv.getUint16(pos+10,true),compSize=dv.getUint32(pos+20,true),nameLen=dv.getUint16(pos+28,true),extraLen=dv.getUint16(pos+30,true),commentLen=dv.getUint16(pos+32,true),localOffset=dv.getUint32(pos+42,true),name=((flags&0x0800)?decoder:new TextDecoder('shift_jis')).decode(buf.slice(pos+46,pos+46+nameLen));pos+=46+nameLen+extraLen+commentLen;if(name.endsWith('/')||name.includes('__MACOSX')||name.startsWith('.'))continue;if(dv.getUint32(localOffset,true)!==0x04034b50)continue;const ln=dv.getUint16(localOffset+26,true),le=dv.getUint16(localOffset+28,true),start=localOffset+30+ln+le,compressed=buf.slice(start,start+compSize);let raw;if(method===0)raw=compressed;else if(method===8)raw=await inflateRaw(compressed);else continue;out.push({name:name.split('/').pop(),path:name,text:()=>Promise.resolve(decoder.decode(raw))});}return out;}
  async function normalizeInputs(fileList){const selected=[...fileList];if(!selected.length)throw new Error('ZIPまたはCSVファイルを選択してください。');const files=[];for(const f of selected){if(f.name.toLowerCase().endsWith('.zip'))files.push(...await unzipFile(f));else if(f.name.toLowerCase().endsWith('.csv'))files.push(f);}if(!files.length)throw new Error('取込対象のCSVが見つかりませんでした。READMEや検査レポートは自動的に除外します。');return files;}
  async function buildPacks(fileList){const files=await normalizeInputs(fileList);const infoFiles=files.filter(f=>f.name.includes(TYPES.info)&&f.name.toLowerCase().endsWith('.csv'));if(!infoFiles.length)throw new Error('基本情報CSVが見つかりませんでした。');const lessonIds=[];for(const f of infoFiles){const rows=parseCsv(await f.text());const id=rows[0]?.lessonId;if(id&&!lessonIds.includes(id))lessonIds.push(id);}const packs=[];for(const lessonId of lessonIds){const lessonFiles=files.filter(f=>f.name.includes(`Lesson${Number(String(lessonId).match(/L(\d+)/)?.[1]||0)}`)||f.name.includes(`Lesson${String(Number(String(lessonId).match(/L(\d+)/)?.[1]||0))}`));const selected={};for(const [key,label] of Object.entries(TYPES)){const source=key==='rules'?files:lessonFiles;const f=pickLatest(source,label);if(!f){if(OPTIONAL_TYPES.has(key))continue;throw new Error(`${lessonId}：不足ファイル「${label}」`);}selected[key]=f;}const data={tables:[],notes:[]};for(const [key,f] of Object.entries(selected))data[key]=parseCsv(await f.text());if(data.info[0]?.lessonId!==lessonId)continue;for(const key of ['vocab','sentences','questions','summaries','quick','gachi','chunks','tables','notes']){if(data[key].some(r=>r.lessonId&&r.lessonId!==lessonId))throw new Error(`${lessonId}：${key} CSVに別Lessonのデータが混在しています。`);}packs.push({lessonId,title:data.info[0]?.title||lessonId,lessonOrder:Number(data.info[0]?.lessonOrder||999),updatedAt:new Date().toISOString(),files:Object.values(selected).map(f=>f.name),ignoredCount:Math.max(0,files.length-new Set(Object.values(selected).map(f=>f.path||f.name)).size),data});}if(!packs.length)throw new Error('Lessonデータを判定できませんでした。');return packs;}
  async function savePack(pack){const db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(pack);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});return pack;}
  async function savePacks(packs){for(const p of packs)await savePack(p);return packs;}
  async function loadAll(){const db=await openDb();const rows=await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});return rows.sort((a,b)=>(a.lessonOrder||999)-(b.lessonOrder||999));}
  async function remove(lessonId){const db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(lessonId);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});}
  window.RulesStore={TYPES,parseCsv,buildPacks,savePack,savePacks,loadAll,remove};
})();
